config/routes.rb
Sitemap::Application.routes.draw do

    
  match '/about',   :to => 'pages#about'

  match '/ed',   :to => 'pages#ed'
  
    match '/medhome',  :to => 'pages#medhome'  

  match '/research',   :to => 'pages#research'

  match '/patient',   :to => 'pages#patient'

  match '/life',   :to => 'pages#life'
  
    match '/people',  :to => 'pages#people'

  match '/news',   :to => 'pages#news'

  match '/why',   :to => 'pages#why'
  

  root :to => 'pages#home'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def about
     @title = "About Us"
  end

  def ed
     @title = "Education and Training"
  end

  def research
     @title = "Research"
  end

  def patient
     @title = "Patient Care"
  end

  def life
     @title = "Life @ UTSW"
  end

  def news
     @title = "News and Events"
  end

  def why
     @title = "Why Here?"
  end
  
  def medhome
      @title = "Medical School"
   end
   
   def people
       @title = "People"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_ed.html.erb
<nav class="round">
  <ul>
		<li><%= link_to "Medical School", medhome_path %></li>
      <li><%= link_to "Graduate School", '#' %></li>
      <li><%= link_to "School of Health Professions", '#' %></li>
		<li><%= link_to "Departments and Centers", '#' %></li>
		<li><%= link_to "Programs", '#' %></li>
  </ul>
</nav>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Footer Nav", '#' %></li>
      <li><%= link_to "Goes Here", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="round">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Education and Training", ed_path %></li>
		<li><%= link_to "Research", research_path %></li>
		<li><%= link_to "Patient Care", patient_path %></li>
		<li><%= link_to "Life @ UTSW", life_path %></li>
	    <li><%= link_to "Why Here?", why_path %></li>
		<li><%= link_to "News and Events", news_path %></li>
      </ul>
    </nav>
</header>

app/views/layouts/_life.html.erb
<nav class="round">
	<ul>
        <li><%= link_to "People", people_path %></li>
        <li><%= link_to "Your Life", '#' %></li>
        <li><%= link_to "Academic Life", '#' %></li>
		<li><%= link_to "Campus Life", '#' %></li>
		<li><%= link_to "Dallas Life", '#' %></li>
		 <li><%= link_to "Get Involved", '#' %></li>
	     <li><%= link_to "Visiting UTSW", '#' %></li>
	     <li><%= link_to "Video Library", '#' %></li>
    </ul>
</nav>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UTSW Sitemap | <%= @title %></title>
    <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
</head>
<body>
	<div class="container">
	  <%= render 'layouts/header' %>
	<section class="round">
	  <%= yield %>
	</section>
	<%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/pages/MedSchool/medhome.html.erb
<h1><%= @title %></h1>
<div class="sub1">
	<ul>
        <li><%= link_to "About the School", '#' %></li>
        <li><%= link_to "Admissions", '#' %></li>
        <li><%= link_to "Alumni", '#' %></li>
		<li><%= link_to "Curriculum", '#' %></li>
		<li><%= link_to "Residency", '#' %></li>
		<li><%= link_to "Fellowships", '#' %></li>
		<li><%= link_to "Residency", '#' %></li>
    </ul>
</div>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<div class="sub1">
	<ul>
        <li><%= link_to "Presidents Message", '#' %></li>
        <li><%= link_to "Mission and History", '#' %></li>
        <li><%= link_to "Administration and Offices", '#' %></li>
		<li><%= link_to "Facts and Figures", '#' %></li>
        <li><%= link_to "Giving", '#' %></li>
        <li><%= link_to "Career", '#' %></li>
		<li><%= link_to "Diversity", '#' %></li>
        <li><%= link_to "Maps and Directions", '#' %></li>
        <li><%= link_to "Contact Us", '#' %></li>
    </ul>
</div>

app/views/pages/ed.html.erb
<h1><%= @title %></h1>
<div class="sub1">
	<ul>
        <li><%= link_to "Medical School", medhome_path %></li>
        <li><%= link_to "Graduate School", '#' %></li>
        <li><%= link_to "School of Health Professions", '#' %></li>
		<li><%= link_to "Departments and Centers", '#' %></li>
		<li><%= link_to "Programs", '#' %></li>
    </ul>
</div>

app/views/pages/home.html.erb
<h1><%= @title %></h1>

app/views/pages/life.html.erb
<h1><%= @title %></h1>

app/views/pages/medhome.html.erb
<div id="primary2">
	<%= render 'layouts/ed' %>
</div>

<h1><%= @title %></h1>

<div id="sub1">
	<ul>
        <li><%= link_to "About the School", '#' %></li>
        <li><%= link_to "Admissions", '#' %></li>
        <li><%= link_to "Alumni", '#' %></li>
		<li><%= link_to "Curriculum", '#' %></li>
		<li><%= link_to "Residency", '#' %></li>
		<li><%= link_to "Fellowships", '#' %></li>
		<li><%= link_to "Residency", '#' %></li>
    </ul>
</div>

app/views/pages/news.html.erb
<h1><%= @title %></h1>
<div class="sub1">
	<ul>
        <li><%= link_to "News", '#' %></li>
        <li><%= link_to "Events", '#' %></li>
    </ul>
</div>

app/views/pages/patient.html.erb
<h1><%= @title %></h1>
<div class="sub1">
	<ul>
        <li><%= link_to "UTSW Hospitals and Clinics", '#' %></li>
        <li><%= link_to "Health Care Professionals", '#' %></li>
        <li><%= link_to "Health Library", '#' %></li>
    </ul>
</div>

app/views/pages/people.html.erb
<div id="primary2">
	<%= render 'layouts/life' %>
</div>

<h1><%= @title %></h1>
<div class="sub1">
	<ul>
        <li><%= link_to "Profiles", '#' %></li>
        <li><%= link_to "Q&A", '#' %></li>
        <li><%= link_to "Videos", '#' %></li>
		<li><%= link_to "Innovation @ Work", '#' %></li>
    </ul>
</div>

app/views/pages/research.html.erb
<h1><%= @title %></h1>
<div id="sub1">
	<ul>
        <li><%= link_to "Research Highlights", '#' %></li>
        <li><%= link_to "Research Opportunities", '#' %></li>
        <li><%= link_to "Core Facilities", '#' %></li>
		<li><%= link_to "Technology Development", '#' %></li>
		<li><%= link_to "Research Administration", '#' %></li>
		<li><%= link_to "Postdoctoral Training", '#' %></li>
    </ul>
</div>

app/views/pages/why.html.erb
<h1><%= @title %></h1>
<div class="sub1">
	<ul>
        <li><%= link_to "Awards and Honors", '#' %></li>
    </ul>
</div>